runtime: nodejs10

instance_class: B1

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always

- url: /.*
  static_files: www/index.html
  upload: www/(.*)

basic_scaling:
  max_instances: 1
  idle_timeout: 5m
